name: Check policy
on:
  pull_request:
  push:
    branches:
      - main
      - hotfix/*
      - work/check-policy  # For development

jobs:
  policy:
    uses: lengau/starflow/.github/workflows/policy.yaml@work/CRAFT-3602/test-workflows
  python-scans:
    name: Security scan
    uses: canonical/starflow/.github/workflows/scan-python.yaml@main
